### ISSUE TITLE
Migrate OSHI from JNA to the FFM backend

### ISSUE THREAD

**Issue by Krillsson** [Krillsson/sys-API#280]
`oshi-core-ffm` replaces JNA with the Java 22+ Foreign Function & Memory API. It requires JDK 25, so this also uplifts the toolchain (Gradle 9, Kotlin 2.x, JDK 25 in CI and packaging).

Keeping `oshi-core` alongside it so `SystemInfoFactory` can fall back to JNA, and so the GraalVM native image stays on the proven JNA path.

**Comment by Krillsson** [comment]
Closing — see #281 for the attempt.

Findings worth keeping:

- Building on JDK 25 needs Gradle 9.1+. No Gradle 8.x can compile a Groovy build script on 25 (8.8 and 8.14.3 both fail with 'Unsupported class file major version 69' out of Groovy's ASM). Watch out when testing this: with an unchanged build.gradle, Gradle reuses the cached compiled script and appears to succeed on 25.
- Gradle 9 breaks the org.hibernate.orm plugin. 6.5.3 and 6.6.x fail with NoSuchMethodError: ResolvedConfiguration.getFiles(). The only version that works is 7.4.5.Final, which pulls hibernate-core to 7.4.5 while Spring Boot 3.5 pins hibernate-community-dialects (the SQLite dialect) at 6.6.39. Getting onto Gradle 9 therefore means Spring Boot 4, or dropping bytecode enhancement.
- FFM only needs a Java 25 runtime, not a Java 25 build, so the toolchain uplift was avoidable — the build can stay on 21 and only the shipped runtimes move.
- SystemInfoFactory.create() does not give a free JNA fallback on older JDKs. It catches ServiceConfigurationError/RuntimeException, but on JDK < 25 the failure is an UnsupportedClassVersionError thrown from ServiceLoader.hasNext(), outside its try block, so the app hard-fails at startup without an explicit LinkageError guard.
- nativeCompile does work with 7.4.2 once oshi-core-ffm is excluded from the nativeImageClasspath — GraalVM built the binary fine in CI.
